### ISSUE TITLE
I have changed my git data but nothing changes

### ISSUE THREAD

**Issue by Veenty** [JuliaCI/PkgTemplates.jl#354]
I changed my git data (.name and .user) but in the moment that I'm creating a template, PkgTemplates is not recognizing this change. When I do ?Templates I see that

user::AbstractString="": GitHub (or other code hosting service)
       username. The default value comes from the global Git config
       (github.user). If no value is obtained, many plugins that use
       this value will not work.

    •  authors::Union{AbstractString, Vector{<:AbstractString}}="Veenty
       <vicentegomezh@gmail.com> and contributors": Package authors.
       Like user, it takes its default value from the global Git config
       (user.name and user.email).

How can I make the user thing recognize my user?

**Comment by a2k42** [comment]
Is this the same issue as https://github.com/JuliaCI/PkgTemplates.jl/issues/327

**Comment by oxinabox** [comment]
Closing this now because I assume it has been resolved, without comment from here.
If not, please repopen and  post the full command you are running (or better yet a MWE), and the outputs of running it.


Sorry this got missed, for a while the package was without active maintainers.
Its still pretty light on them.
